INSERT INTO institution (userId, name, rating, description) VALUES (289, 'Санкт-Петербургский политехнический университет Петра Великого', 9.1, '');
INSERT INTO institution (userId, name, rating, description) VALUES (354, 'Санкт-Петербургский национальный исследовательский университет информационных технологий',  механики и оптики, '');
INSERT INTO institution (userId, name, rating, description) VALUES (825, 'Санкт-Петербургский государственный экономический университет', 7.9, '');
INSERT INTO institution (userId, name, rating, description) VALUES (555, 'Санкт-Петербургский Горный университет', 6.9, '');
INSERT INTO institution (userId, name, rating, description) VALUES (880, 'Санкт-Петербургский государственный университет телекоммуникаций им. проф. М.А.Бонч-Бруевича', 6.6, '');
INSERT INTO institution (userId, name, rating, description) VALUES (265, 'Санкт-Петербургский университет технологий управления и экономики', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (716, 'Санкт-Петербургский университет государственной противопожарной службы МЧС России', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (350, 'Санкт-Петербургский государственный архитектурно-строительный университет', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (285, 'Санкт-Петербургский военный институт внутренних войск МВД РФ', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (430, 'Военный инженерно-технический институт Военной академии материально-технического обеспечения имени генерала армии А. В. Хрулева', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (488, 'Российский государственный педагогический университет имени А. И. Герцена', 6.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (435, 'Смольный институт Российской академии образования', 6.4, '');
INSERT INTO institution (userId, name, rating, description) VALUES (856, 'Санкт-Петербургский государственный электротехнический университет «ЛЭТИ» им. В.И. Ульянова (Ленина)', 6.1, '');
INSERT INTO institution (userId, name, rating, description) VALUES (890, 'Северо-Западный государственный медицинский университет им. И. И. Мечникова', 6, '');
INSERT INTO institution (userId, name, rating, description) VALUES (884, 'Санкт-Петербургский гуманитарный университет профсоюзов', 5.8, '');
INSERT INTO institution (userId, name, rating, description) VALUES (565, 'Военная академия связи имени маршала Советского Союза С. М. Буденного', 5.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (899, 'Военный институт (военно-морской) Военно-морской академии имени адмирала флота Советского Союза Н. Г. Кузнецова', 5.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (474, 'Михайловская военная артиллерийская академия', 5.5, '');
INSERT INTO institution (userId, name, rating, description) VALUES (894, 'Первый Санкт-Петербургский государственный медицинский университет имени академика И. П. Павлова', 5.5, '');
